title: Astro
description: Astro is a web framework for building content-driven websites including blogs, marketing, and e-commerce sites. Learn how to set it up with Sentry.
sdk: sentry.javascript.astro
categories:
  - browser
  - server
