version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 0 # security updates only
    directory: '/'
    schedule:
      # Going to start with a high interval, and then tone it back
      interval: daily
    reviewers:
      - '@getsentry/docs'
    labels: []
    # Group dependency updates together in one PR
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
    groups:
      # The name of the group, it will be used in PR titles and branch
      babel-dependencies:
        patterns:
          - '@babel/*'
      emotion-dependencies:
        patterns:
          - '@emotion/*'
      mdx-dependencies:
        patterns:
          - '@mdx-js/*'
      ts-eslint-dependencies:
        patterns:
          - '@typescript-eslint/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every week
      interval: 'daily'
