exclude: '\.snap|node_modules$'
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: flake8
      - id: fix-encoding-pragma
        args: ["--remove"]
  - repo: git://github.com/getsentry/pre-commit-hooks
    rev: f3237d2d65af81d435c49dee3593dc8f03d23c2d
    hooks:
      - id: prettier
        entry: gatsby/node_modules/.bin/prettier
      # - id: eslint
      #   entry: gatsby/node_modules/.bin/eslint
