url: ''

assets:
  compression: false
  digest: false
  source_maps: false
  precompile:
    - '*.map'
    - '*.ico'
    - 'meta/*'
  raw_precompile:
    - '*.map'
    - '*.ico'
    - 'meta/*'


collections:
  dev_components:
    output: true

include:
  - _dev
  - _mock_api
