title: Sentry Documentation
description: >-
  Learn how to use Sentry, configure Sentry clients, and contribute to the open
  source project on GitHub
meta_image: default.png
baseurl: ''
url: 'https://docs.sentry.io'
twitter_username: getsentry
home_url: https://sentry.io
release_service: https://release-registry.services.sentry.io

# Build settings
port: 9001
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-assets
  - jekyll-extlinks
  - liquid-md5

permalink: /:slug/

timezone: America/Los_Angeles

source: src
collections_dir: collections

collections:
  documentation:
    output: true

defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: doc
  - scope:
      path: ''
      type: documentation
    values:
      layout: doc
      toc: true
      permalink: /:path/
  - scope:
      path: collections/_documentation/clients/*
      type: documentation
    values:
      layout: legacy-client
  - scope:
      path: collections/_documentation/api/*/*
      type: documentation
    values:
      layout: api

  # Development mode collections. These exist here because placing them in
  # _config.dev.yml will clober the entire defaults object. The collections
  # object does not get clobbered so we use that to only load the dev
  # in dev mode, and these defaults here are not used in production.
  - scope:
      path: ''
      type: dev_components
    values:
      layout: dev/default
      permalink: /:path/
  - scope:
      path: collections/_dev_components/markdown-styleguide/*
    values:
      layout: doc

assets:
  source_maps: false # Prefer webpack source maps
  plugins:
    css:
      autoprefixer:
        browsers:
          - 'last 2 versions'
          - 'ie > 9'
  precompile:
    - '*.map'
    - '*.ico'
    - 'meta/*'
  raw_precompile:
    - '*.map'
    - '*.ico'
    - 'meta/*'

extlinks:
  attributes: { rel: nofollow }
  rel_exclude: ['sentry.io', 'getsentry.com']

algolia:
  application_id: OOK48W9UCL
  index_name: sentry-docs
  settings:
    attributesToHighlight:
      - title
      - headings
      - content
      - html
      - categories
      - tags
    highlightPreTag: '<strong class="text-danger">'
    highlightPostTag: '</strong>'
    attributesToSnippet:
      - content:20
    attributeForDistinct: url
    attributesForFaceting:
      - searchable(categories)
      - searchable(tags)

# Hack to give us an empty array prototype
#  {% assign labels = site.Array
#    | push: 'Foo'
#    | push: 'Bar'
#    | push: 'Bat'
#  %}
Array: []

exclude:
  - _js
