title: Capacitor
description: Sentry's Capacitor SDK enables automatic reporting of errors, exceptions, and messages. It includes native crash support on iOS and Android.
sdk: sentry.javascript.capacitor
categories:
  - mobile
  - browser
