title: Next.js
description: Next.js is a flexible React framework that gives you building blocks to create fast, full-stack web applications. Learn how to set it up with Sentry.
sdk: sentry.javascript.nextjs
categories:
  - browser
  - server
