blank_issues_enabled: false
contact_links:
  - name: Support Request
    url: https://sentry.io/support
    about: Use our dedicated support channel for paid accounts.
  - name: Ask a question about self-hosted Sentry
    url: https://github.com/getsentry/self-hosted/issues/new/choose
    about: Please use GitHub Issues for questions about self-hosted Sentry.
  - name: An issue with one of the SDKs
    url: https://git.io/JtlVm
    about: Please use the relevant SDK repository to report any issues.
