title: Remix
description: Sentry's Remix SDK enables automatic reporting of errors and exceptions, as well as the performance metrics for both client and server side operations.
sdk: sentry.javascript.remix
categories:
  - browser
  - server
