title: Angular
description: "Angular is a web framework that empowers developers to build fast, reliable applications. Learn how to set it up with Sentry."
sdk: sentry.javascript.angular
categories:
  - browser
