title: Browser JavaScript
description: Learn how to manually set up Sentry in your JavaScript app and capture your first errors.
platformTitle: JavaScript
sidebar_title: JavaScript
caseStyle: camelCase
supportLevel: production
sdk: 'sentry.javascript.browser'
language: typescript
categories:
  - javascript
  - browser
