name: Enforce Version Conventions

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-version-convention:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v3 # v2

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Run script for checking conventions
        run: bun scripts/check-version-conventions.ts
